### ISSUE TITLE
Ocean Liners Compatability

### ISSUE THREAD

**Issue by xavier630** [GopherAtl/rso-mod-mod#2]
Hi Will!

First, I'd like to say, I really love RSO, it's so much fun to play with (sometimes I do miss having a colourful map though).

Anyway, I was wondering if you'd please be able to add compatability for Ocean Liners' Sea-oil. This is currently generated with the same noise layer as crude oil although I'm happy adding a few lines of code to give it its own one if necessary. 

The resource is defined at the top here: https://github.com/xavier630/Ocean-Liners-Factorio/blob/master/OceanLiners_0.1.8/prototypes/entity/entities2.lua

Is there anything you need to know to make it work?

The other thing is biter bases. I add code to the data-final-fixes to give them a collision mask with water-tiles so that they can't spawn on the ocean in  my mod (which has been changed). I think your mod might overwrite what I've done possibly. If your mod is changing them, could we find a solution?

```
local biter = data.raw["unit-spawner"] -- make sure biter lairs don't spawn on water.
for k,v in pairs(biter) do
  v.collision_mask={"water-tile", "player-layer"} --only the spawners, not the bugs
end
```

Anyway, let me know what you think,
Xavier

**Comment by GopherAtl** [comment]
Not my mod, I just made this fork when I was playing with some ideas... atm I can't even remember what the change *was*... something related to some multiplayer mode, or something? IDK xD

**Comment by xavier630** [comment]
Yeah, don't worry haha. I found the original shortly after asking and commented there.
